### ISSUE TITLE
Train with GPU

### ISSUE THREAD

**Issue by kexul** [andrrizzi/tfep-revisited-2021#1]
Hi guys, thanks for your great work! I've read your paper and would like to reproduce the double-well result. I just cloned the code and run the script by: 
```
python double_well.py --job_id 1
```
I found the training was running in CPU, it could be very time-consuming if I train 40 repeats as the paper did. Is it possible to run it with GPU? My machine already has cuda-enabled torch.

**Comment by kexul** [comment]
Here is my result of 1 repeat, which differs a lot compared to the result in the paper. 
![企业微信截图_16297925884681](https://user-images.githubusercontent.com/5920217/130581051-f2b9e65e-645d-494e-b308-1960d5db6085.png)

**Comment by andrrizzi** [comment]
Hi @kexul . You'll have to do a lot more repeats to replicate the results. Those are based on 40 different nets and 50 evaluation dataset for each net (it's better described in the SI than in the main text), and then the predictions are averaged to compute the uncertainty.

It should be possible to run the PyTorch model on GPU as well. It might be as simple as calling `toy_model.to(device)`. The docs of PyTorch should be helpful. The net in this case is not that deep but it might give you some speedup over the 10000 cycles of training.

**Comment by kexul** [comment]
Thanks, I'll try to repeat more.

**Comment by kexul** [comment]
Ok, I got a similar graph as your paper, when using a lot more repeats. I terminated my experiment at 500 train samples since it's still quite slow though I've moved the computation to GPU. 

Quite impressive work, thanks for that, and your open-source. 

![企业微信截图_16310006473401](https://user-images.githubusercontent.com/5920217/132305366-05498d05-ccc6-420b-bd5e-d6999ee9c8f9.png)

**Comment by andrrizzi** [comment]
I'm glad you could reproduce the result and that the code was helpful!
