### ISSUE TITLE
Is this a typo? 

### ISSUE THREAD

**Issue by kexul** [andrrizzi/tfep-revisited-2021#2]
Hi, in these lines, the parameter `p` is never used, is this a typo?
https://github.com/andrrizzi/tfep-revisited-2021/blob/9d318976905761c1bf2c60e61b08c01946dec2fd/scripts/double_well.py#L711-L714

**Comment by andrrizzi** [comment]
It is a typo! Thanks for catching that!

The script works anyway because `_sample_util` is always called with `p=p1` and `p1` is defined globally in `__main__`, but I will fix it right away in case people need to tweak the code.
